name: Playit-GG-Revamped
version: 2.0.0
main: gg.playit.minecraft.PlayitBukkit
author: ThaYTOfficial
description: Revamped - Makes your server public without port forwarding
api-version: "1.13"
folia-supported: true
softdepend: [Geyser-Spigot]

commands:
  playit:
    description: Configure playit.gg tunnel
    usage: /playit
    permission: Operators
    permission-message: You must be a server operator to run the playit command
